Repository team-ecolink/map2zero-backend, pull requests merged in 2024-02, with the labels that each got.

#56 [Feat] `GET /stores/popular` API 추가
  src/main/java/com/ecolink/core/store/controller/StoreSearchController.java
  src/main/java/com/ecolink/core/store/repository/StoreRepository.java
  src/main/java/com/ecolink/core/store/service/StoreSearchService.java
Labels: enhancement

#62 [Feat] `PUT /avatars/photos` API 추가
  src/main/java/com/ecolink/core/avatar/controller/AvatarController.java
  src/main/java/com/ecolink/core/avatar/domain/Avatar.java
  src/main/java/com/ecolink/core/avatar/domain/ProfilePhoto.java
  src/main/java/com/ecolink/core/avatar/dto/PutProfilePhotoRequest.java
  src/main/java/com/ecolink/core/avatar/repository/AvatarRepository.java
  src/main/java/com/ecolink/core/avatar/service/AvatarInfoService.java
  src/main/java/com/ecolink/core/avatar/service/AvatarService.java
  src/main/java/com/ecolink/core/avatar/service/ProfilePhotoService.java
Labels: enhancement

#64 [Fix] `Swagger`에서 `PUT /avatars/photos` API 테스트할 수 있도록 수정
  src/main/java/com/ecolink/core/avatar/controller/AvatarController.java
  src/main/java/com/ecolink/core/common/config/swagger/annotation/SwaggerBody.java
  src/main/resources/application-swagger.yml
Labels: bug

#35 [Feat] `GET /stores/{storeId}/reviews` 리뷰 리스트 조회 API 추가
  src/main/java/com/ecolink/core/like/repository/ReviewLikeRepository.java
  src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
  src/main/java/com/ecolink/core/review/controller/ReviewController.java
  src/main/java/com/ecolink/core/review/domain/Review.java
  src/main/java/com/ecolink/core/review/dto/ReviewTagDto.java
  src/main/java/com/ecolink/core/review/dto/ReviewWriterDto.java
  src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
  src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
  src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: enhancement

#58 [Refactor] `DELETE` 메서드 `Path Variable`에서 `Http Body`로 수정, 경로 수정
  src/main/java/com/ecolink/core/store/controller/SearchHistoryController.java
  src/main/java/com/ecolink/core/store/dto/request/SearchHistoryRequest.java
Labels: enhancement

#68 [Feat] 다중 파일 업로드 서비스 추가
  src/main/java/com/ecolink/core/file/domain/MultiPhoto.java
  src/main/java/com/ecolink/core/file/domain/MultiPhotoContainer.java
  src/main/java/com/ecolink/core/file/factory/MultiPhotoFactory.java
  src/main/java/com/ecolink/core/file/service/MultiPhotoService.java
Labels: enhancement

#69 [Feat] 로그아웃 URI 변경, 성공 핸들러 추가
  src/main/java/com/ecolink/core/auth/handler/JsonLogoutSuccessHandler.java
  src/main/java/com/ecolink/core/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ecolink/core/auth/service/JsonResponseMaker.java
  src/main/java/com/ecolink/core/common/config/security/SecurityConfig.java
Labels: enhancement

#71 [Feat] `POST /managers` API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/common/error/exception/ManagerApplicationException.java
  src/main/java/com/ecolink/core/manager/controller/ManagerController.java
  src/main/java/com/ecolink/core/manager/domain/Manager.java
  src/main/java/com/ecolink/core/manager/domain/StoreRegistration.java
  src/main/java/com/ecolink/core/manager/dto/request/ManagerApplicationRequest.java
  src/main/java/com/ecolink/core/manager/dto/request/StoreRegistrationRequest.java
  src/main/java/com/ecolink/core/manager/repository/ManagerRepository.java
  src/main/java/com/ecolink/core/manager/service/ManagerService.java
  src/main/java/com/ecolink/core/manager/service/StoreRegistrationRepository.java
  src/main/java/com/ecolink/core/manager/service/StoreRegistrationService.java
  src/main/java/com/ecolink/core/user/domain/User.java
  src/main/java/com/ecolink/core/user/repository/UserRepository.java
  src/main/java/com/ecolink/core/user/service/UserService.java
Labels: enhancement

#72 [Feat] `GET /tags` API 추가
  src/main/java/com/ecolink/core/tag/constant/TagCategory.java
  src/main/java/com/ecolink/core/tag/controller/TagController.java
  src/main/java/com/ecolink/core/tag/controller/TagService.java
  src/main/java/com/ecolink/core/tag/dto/request/GetTagRequest.java
  src/main/java/com/ecolink/core/tag/dto/response/GetTagResponse.java
  src/main/java/com/ecolink/core/tag/repository/TagRepository.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#73 [Hotfix] 응답 JSON 프로퍼티명 및 필드명 통일
  src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
Labels: enhancement

#74 [Feat] `GET /my-page/reviews` API 추가
  src/main/java/com/ecolink/core/avatar/controller/MyPageController.java
  src/main/java/com/ecolink/core/avatar/dto/request/MyPageReviewRequest.java
  src/main/java/com/ecolink/core/avatar/dto/response/MyPageReviewResponse.java
  src/main/java/com/ecolink/core/bookmark/dto/response/StoreInfoDto.java
  src/main/java/com/ecolink/core/like/domain/ReviewLike.java
  src/main/java/com/ecolink/core/review/repository/ReviewJpaRepository.java
  src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
Labels: enhancement

#59 [Feat] `GET /stores/{storeId}/events` 이벤트 리스트 조회 API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/event/constant/EventStatus.java
  src/main/java/com/ecolink/core/event/controller/EventController.java
  src/main/java/com/ecolink/core/event/domain/Event.java
  src/main/java/com/ecolink/core/event/dto/request/GetEventRequest.java
  src/main/java/com/ecolink/core/event/dto/response/GetEventListResponse.java
  src/main/java/com/ecolink/core/event/repository/EventJpaRepository.java
  src/main/java/com/ecolink/core/event/repository/EventRepository.java
  src/main/java/com/ecolink/core/event/service/EventSearchService.java
  src/main/java/com/ecolink/core/event/service/EventService.java
Labels: enhancement

#81 [Feat] 권한 계층 기능 추가
  src/main/java/com/ecolink/core/common/config/security/SecurityConfig.java
Labels: enhancement

#76 [Feat] `POST /reviews` API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/common/error/exception/PhotoLimitExceededException.java
  src/main/java/com/ecolink/core/file/constant/FilePath.java
  src/main/java/com/ecolink/core/product/service/StoreProductSearchService.java
  src/main/java/com/ecolink/core/review/controller/ReviewController.java
  src/main/java/com/ecolink/core/review/domain/Review.java
  src/main/java/com/ecolink/core/review/domain/ReviewPhoto.java
  src/main/java/com/ecolink/core/review/domain/ReviewTag.java
  src/main/java/com/ecolink/core/review/dto/request/CreateReviewRequest.java
  src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
  src/main/java/com/ecolink/core/review/repository/ReviewJpaRepository.java
  src/main/java/com/ecolink/core/review/repository/ReviewTagRepository.java
  src/main/java/com/ecolink/core/review/service/ReviewCreateService.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
  src/main/java/com/ecolink/core/review/service/ReviewTagService.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/tag/controller/TagController.java
  src/main/java/com/ecolink/core/tag/service/TagService.java
Labels: enhancement

#77 [Feat] `store_name`, `product_name` 인덱스 적용
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/tag/domain/Product.java
Labels: enhancement

#84 [Feat] `GET /m/stores/{id}/products` API 추가
  src/main/java/com/ecolink/core/product/controller/StoreProductController.java
  src/main/java/com/ecolink/core/product/domain/StoreProduct.java
  src/main/java/com/ecolink/core/product/domain/StoreProductTag.java
  src/main/java/com/ecolink/core/product/repository/StoreProductJpaRepository.java
  src/main/java/com/ecolink/core/product/service/StoreProductSearchService.java
  src/main/java/com/ecolink/core/product/service/StoreProductService.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#88 [Feat] `POST /m/stores/{id}/products` API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/common/error/exception/InvalidProductNameException.java
  src/main/java/com/ecolink/core/common/error/exception/InvalidProductPriceException.java
  src/main/java/com/ecolink/core/file/constant/FilePath.java
  src/main/java/com/ecolink/core/product/controller/StoreProductController.java
  src/main/java/com/ecolink/core/product/domain/StoreProduct.java
  src/main/java/com/ecolink/core/product/domain/StoreProductPhoto.java
  src/main/java/com/ecolink/core/product/dto/request/PostStoreProductRequest.java
  src/main/java/com/ecolink/core/product/repository/ProductRepository.java
  src/main/java/com/ecolink/core/product/service/ProductNameService.java
  src/main/java/com/ecolink/core/product/service/ProductPriceService.java
  src/main/java/com/ecolink/core/product/service/ProductService.java
  src/main/java/com/ecolink/core/product/service/StoreProductCudService.java
  src/main/java/com/ecolink/core/product/service/StoreProductService.java
  src/main/java/com/ecolink/core/tag/domain/Product.java
Labels: enhancement

#67 [Refactor] `GET /stores/{id}` 매장 상품 갯수, 지도 URL 추가
  src/main/java/com/ecolink/core/store/controller/StoreController.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/store/dto/response/StoreDetailResponse.java
Labels: enhancement

#87 [Feat] `POST /m/stores/{id}/events` API 추가
  src/main/java/com/ecolink/core/auth/token/UserPrincipal.java
  src/main/java/com/ecolink/core/event/controller/EventController.java
  src/main/java/com/ecolink/core/event/domain/Event.java
  src/main/java/com/ecolink/core/event/domain/EventPhoto.java
  src/main/java/com/ecolink/core/event/dto/request/AddEventRequest.java
  src/main/java/com/ecolink/core/event/dto/response/GetEventListResponse.java
  src/main/java/com/ecolink/core/event/service/EventAddService.java
  src/main/java/com/ecolink/core/file/constant/FilePath.java
  src/main/java/com/ecolink/core/review/dto/request/CreateReviewRequest.java
Labels: enhancement

#89 [Feat] 추가 기획 사항 반영
  src/main/java/com/ecolink/core/product/service/StoreProductService.java
  src/main/java/com/ecolink/core/store/domain/Store.java
Labels: enhancement

#86 [Feat]`GET /events/{id}` 이벤트 상세 조회 API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/event/controller/EventController.java
  src/main/java/com/ecolink/core/event/dto/response/GetEventResponse.java
  src/main/java/com/ecolink/core/event/repository/EventRepository.java
  src/main/java/com/ecolink/core/event/service/EventSearchService.java
  src/main/java/com/ecolink/core/event/service/EventService.java
Labels: enhancement

#95 [Feat] `GET /stores/map` API 추가
  build.gradle
  src/main/java/com/ecolink/core/geo/service/GeometryService.java
  src/main/java/com/ecolink/core/store/controller/StoreSearchController.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/store/dto/MapStoreInfoDto.java
  src/main/java/com/ecolink/core/store/dto/request/MapQueryRequest.java
  src/main/java/com/ecolink/core/store/repository/StoreJpaRepository.java
  src/main/java/com/ecolink/core/store/service/StoreSearchService.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#90 [Feat] `GET /m/stores/{id}/events` 추가
  src/main/java/com/ecolink/core/event/constant/EventStatus.java
  src/main/java/com/ecolink/core/event/controller/EventController.java
  src/main/java/com/ecolink/core/event/dto/request/GetManagerEventRequest.java
  src/main/java/com/ecolink/core/event/service/EventSearchService.java
  src/main/java/com/ecolink/core/event/service/EventService.java
Labels: enhancement

#92 [Feat] `GET /stores/trend` API 추가
  src/main/java/com/ecolink/core/store/controller/StoreController.java
  src/main/java/com/ecolink/core/store/dto/response/StoreTrendResponse.java
  src/main/java/com/ecolink/core/store/service/StorePhotoService.java
  src/main/java/com/ecolink/core/store/service/StoreTrendService.java
Labels: enhancement

#96 [Feat] `GET /stores/map/nearest` API 추가
  src/main/java/com/ecolink/core/common/util/AuthorityUtil.java
  src/main/java/com/ecolink/core/store/controller/StoreSearchController.java
Labels: enhancement

#97 [Feat] `GET /managers/stores` API 추가
  src/main/java/com/ecolink/core/auth/token/UserPrincipal.java
  src/main/java/com/ecolink/core/manager/controller/ManagerController.java
  src/main/java/com/ecolink/core/manager/repository/ManagerRepository.java
  src/main/java/com/ecolink/core/manager/service/ManagerService.java
Labels: enhancement

#93 [Feat] `GET /products/today`, `GET /products/my` API 추가
  src/main/java/com/ecolink/core/product/service/StoreProductService.java
  src/main/java/com/ecolink/core/product_recommend/constant/RecommendType.java
  src/main/java/com/ecolink/core/product_recommend/controller/ProductRecommendController.java
  src/main/java/com/ecolink/core/product_recommend/domain/ProductRecommend.java
  src/main/java/com/ecolink/core/product_recommend/dto/ProductInfoDto.java
  src/main/java/com/ecolink/core/product_recommend/repository/ProductRecommendRepository.java
  src/main/java/com/ecolink/core/product_recommend/service/ProductRecommendService.java
  src/main/java/com/ecolink/core/store/controller/StoreController.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#101 [FEAT] 기획 수정 사항 반영
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/product/dto/request/PostStoreProductRequest.java
  src/main/java/com/ecolink/core/product/service/ProductPriceService.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/store/dto/response/StoreDetailResponse.java
Labels: enhancement

#102 [Feat] CORS 정책 변경
  src/main/java/com/ecolink/core/common/config/security/SecurityConfig.java
Labels: bug, enhancement

#103 [Fix] SRID 4326을 기본으로 매핑하도록 변경
  src/main/java/com/ecolink/core/geo/service/GeometryService.java
Labels: enhancement

#106 [Feat] Minor updates
  src/main/java/com/ecolink/core/event/dto/request/GetEventRequest.java
  src/main/java/com/ecolink/core/product/dto/request/GetStoreProductRequest.java
  src/main/java/com/ecolink/core/review/controller/ReviewController.java
Labels: enhancement

#107 [Feat] 소셜로그인 프로필 사진 항목 선택사항으로 변경
  src/main/java/com/ecolink/core/user/constant/UserType.java
Labels: enhancement

#100 [Feat] `GET /my-page/bookmarks` 커서 페이징 추가
  src/main/java/com/ecolink/core/avatar/controller/MyPageController.java
  src/main/java/com/ecolink/core/avatar/dto/request/MyPageBookmarkRequest.java
  src/main/java/com/ecolink/core/avatar/dto/response/MyPageBookmarkResponse.java
  src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
  src/main/java/com/ecolink/core/bookmark/domain/Bookmark.java
  src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
  src/main/java/com/ecolink/core/bookmark/service/BookmarkListService.java
  src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
Labels: enhancement

#111 [Feat] CORS 정책 변경
  src/main/java/com/ecolink/core/common/config/security/SecurityConfig.java
Labels: enhancement

#113 [Feat] 기본 프로필 사진 변경
  src/main/java/com/ecolink/core/avatar/service/ProfilePhotoService.java
Labels: enhancement

#117 [Feat] `GET /curations` API 추가
  src/main/java/com/ecolink/core/admin/constant/RecommendType.java
  src/main/java/com/ecolink/core/admin/controller/CurationController.java
  src/main/java/com/ecolink/core/admin/controller/ProductRecommendController.java
  src/main/java/com/ecolink/core/admin/domain/Curation.java
  src/main/java/com/ecolink/core/admin/domain/ProductRecommend.java
  src/main/java/com/ecolink/core/admin/dto/ProductInfoDto.java
  src/main/java/com/ecolink/core/admin/dto/response/GetCurationResponse.java
  src/main/java/com/ecolink/core/admin/repository/CurationRepository.java
  src/main/java/com/ecolink/core/admin/repository/ProductRecommendRepository.java
  src/main/java/com/ecolink/core/admin/service/CurationService.java
  src/main/java/com/ecolink/core/admin/service/ProductRecommendService.java
  src/main/java/com/ecolink/core/product_recommend/constant/RecommendType.java
Labels: enhancement

#118 [Fix] 좌표가 null 일 경우 핸들링
  src/main/java/com/ecolink/core/store/dto/MapStoreInfoDto.java
  src/main/java/com/ecolink/core/store/repository/StoreJpaRepository.java
Labels: enhancement

#120 [Fix] 판매 중인 상품수만 표시하도록 픽스
  src/main/java/com/ecolink/core/product/repository/StoreProductRepository.java
  src/main/java/com/ecolink/core/product/service/StoreProductService.java
  src/main/java/com/ecolink/core/store/dto/response/StoreDetailResponse.java
  src/main/java/com/ecolink/core/store/service/StoreSearchService.java
Labels: bug

#121 [Feat] `PUT /m/stores/{id}/photos` API 추가
  src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
  src/main/java/com/ecolink/core/file/constant/FilePath.java
  src/main/java/com/ecolink/core/store/controller/StoreController.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/java/com/ecolink/core/store/domain/StorePhoto.java
  src/main/java/com/ecolink/core/store/dto/response/StoreDetailResponse.java
  src/main/java/com/ecolink/core/store/repository/StoreJpaRepository.java
  src/main/java/com/ecolink/core/store/repository/StoreRepository.java
  src/main/java/com/ecolink/core/store/service/StoreCudService.java
  src/main/java/com/ecolink/core/store/service/StorePhotoService.java
  src/main/java/com/ecolink/core/store/service/StoreService.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#122 [Fix] 요일의 `name` 을 응답하도록 수정
  src/main/java/com/ecolink/core/store/dto/OperatingHourDto.java
Labels: bug

#124 [Feat] `POST /likes`, `DELETE /likes` API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/common/error/exception/ReviewLikeAlreadyExistsException.java
  src/main/java/com/ecolink/core/like/controller/ReviewLikeController.java
  src/main/java/com/ecolink/core/like/domain/ReviewLike.java
  src/main/java/com/ecolink/core/like/dto/request/DeleteLikeRequest.java
  src/main/java/com/ecolink/core/like/dto/request/PostLikeRequest.java
  src/main/java/com/ecolink/core/like/repository/ReviewLikeRepository.java
  src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
  src/main/java/com/ecolink/core/review/domain/Review.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#127 [Feat] 닉네임 랜덤 값 추가
  src/main/java/com/ecolink/core/avatar/service/NicknameService.java
Labels: enhancement

#126 [Feat] `DELETE /reviews` API 추가
  src/main/java/com/ecolink/core/common/error/ErrorCode.java
  src/main/java/com/ecolink/core/common/error/exception/AccessDeniedException.java
  src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
  src/main/java/com/ecolink/core/review/controller/ReviewController.java
  src/main/java/com/ecolink/core/review/domain/Review.java
  src/main/java/com/ecolink/core/review/dto/request/DeleteReviewRequest.java
  src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
  src/main/java/com/ecolink/core/review/service/ReviewCudService.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
  src/main/java/com/ecolink/core/store/domain/Store.java
  src/main/resources/application-swagger.yml
Labels: enhancement

#128 [Fix] 사진 용량 리밋 수정
  src/main/resources/application.yml
Labels: bug

#129 [Feat] 기본 타임존 설정 추가
  src/main/java/com/ecolink/core/CoreApplication.java
Labels: enhancement

#130 [Fix] 리뷰 삭제 시 평점에 반영되지 않는 현상 수정
  src/main/java/com/ecolink/core/review/service/ReviewCudService.java
  src/main/java/com/ecolink/core/review/service/ReviewService.java
  src/main/java/com/ecolink/core/store/domain/Store.java
Labels: enhancement

#132 [Feat] 매장 운영 시간 정렬 기능 추가
  src/main/java/com/ecolink/core/store/dto/OperatingHourDto.java
  src/main/java/com/ecolink/core/store/dto/response/StoreDetailResponse.java
Labels: enhancement

#137 [Fix] `StoreProduct` price 필드 형식 변환
  src/main/java/com/ecolink/core/admin/dto/ProductInfoDto.java
  src/main/java/com/ecolink/core/product/dto/response/GetStoreProductResponse.java
  src/main/java/com/ecolink/core/product/util/PriceUtil.java
Labels: enhancement
